version: '3'
services:
  admin:
    container_name: 'human_resource_cms'
    hostname: 'human_resource_cms'
    image: 'huynhdn/human_resource_cms:1.0'
    restart: always
  proxy:
    container_name: 'cms_proxy'
    hostname: 'cms_proxy'
    image: 'nginx:alpine'
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

